name: React Build Pipeline

on:
  push:
    branches:
      - main  # Replace with your desired branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version required for your project

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the React application
      - name: Build React Application
        run: |
          npm run build > build.log 2>&1 || {
            echo "Build failed. Outputting log..."
            cat build.log
            exit 1
          }

      # Step 5: Upload the production build as artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: build/  # Path to the production build folder (adjust if needed)

      # Step 6: Upload build logs as artifacts
      - name: Upload Build Logs
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: build.log
